---
sidebar: sidebar 
permalink: trident-protect/trident-protect-upgrade.html 
keywords: trident, protect, netapp, upgrade, new, version 
summary: 新しい機能やバグ修正を活用するには、Trident Protectを最新バージョンにアップグレードできます。 
---
= Trident Protectのアップグレード
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
新しい機能やバグ修正を活用するには、Trident Protectを最新バージョンにアップグレードできます。

[NOTE]
====
* バージョン24.10からアップグレードすると、アップグレード中に実行されるスナップショットが失敗する可能性があります。この障害により、手動またはスケジュールされた将来のスナップショットの作成が妨げられることはありません。アップグレード中にスナップショットが失敗した場合は、アプリケーションが保護されるように手動で新しいスナップショットを作成できます。
+
潜在的な障害を回避するために、アップグレード前にすべてのスナップショット スケジュールを無効にして、アップグレード後に再度有効にすることができます。ただし、これにより、アップグレード期間中にスケジュールされたスナップショットが失われることになります。

* プライベート レジストリのインストールでは、ターゲット バージョンに必要な Helm チャートとイメージがプライベート レジストリで使用できることを確認し、カスタム Helm 値が新しいチャート バージョンと互換性があることを確認します。詳細については、link:trident-protect-installation.html["プライベートレジストリからTrident Protectをインストールする"]を参照してください。


====
Trident Protectをアップグレードするには、次の手順を実行します。

.手順
. Trident Helm リポジトリを更新します：
+
[source, console]
----
helm repo update
----
. Trident Protect CRD をアップグレードする：
+

NOTE: 25.06より前のバージョンからアップグレードする場合は、CRDがTrident Protect Helmチャートに含まれているため、この手順が必要です。

+
.. このコマンドを実行して、CRDの管理を `trident-protect-crds`から `trident-protect`に移行します：
+
[source, console]
----
kubectl get crd | grep protect.trident.netapp.io | awk '{print $1}' | xargs -I {} kubectl patch crd {} --type merge -p '{"metadata":{"annotations":{"meta.helm.sh/release-name": "trident-protect"}}}'
----
.. このコマンドを実行して `trident-protect-crds`チャートのHelmシークレットを削除します：
+

NOTE: Helm を使用して `trident-protect-crds`チャートをアンインストールしないでください。CRD と関連データが削除される可能性があります。

+
[source, console]
----
kubectl delete secret -n trident-protect -l name=trident-protect-crds,owner=helm
----


. Trident Protectのアップグレード：
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect --version 100.2510.0 --namespace trident-protect
----
+

NOTE: アップグレード中にログレベルを設定するには、アップグレード コマンドに `--set logLevel=debug`を追加します。デフォルトのログレベルは `warn`です。デバッグログは、ログ レベルの変更や問題の再現を必要とせずにNetAppサポートが問題を診断するのに役立つため、トラブルシューティングに推奨されます。


